# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release-dll
endif
export config

PROJECTS := GWEN

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

GWEN: 
	@echo "==== Building GWEN ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f GWEN.make

clean:
	@${MAKE} --no-print-directory -C . -f GWEN.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   release-dll"
	@echo "   debug-dll"
	@echo "   release-static"
	@echo "   debug-static"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GWEN"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
